### ISSUE TITLE
Sets temperature of the wrong tool (single extruder, multiple filament = MMU2)

### ISSUE THREAD

**Issue by Mirarkitty** [kantlivelong/OctoPrint-SetAndWait#3] opened 2020-06-06 20:16 UTC
It seems like the gcode change by SetAndWait adds the tool that's used, but without checking if it's a single extruder system.
```

Send: M190 S85
Send: N124 M104 S250.0 T4*59
Send: M109 S250
Send: N125 G28 W*98
Recv: ok
Send: N126 M105*34
Recv: echo:M104 Invalid extruder 4
T4 reported as invalid, reverting to T3
Recv: ok
Not queuing T3, that tool doesn't exist according to the printer profile or was reported as invalid by the firmware
Send: N127 G80*21
```

Original gcode is "M104 S250.0" without the Tx.

The effect is OctoPrint removing filament switches after this trigger.

**Comment by kantlivelong** [comment] 2020-06-07 20:39
Duplicate of #2 as the issues are related.

**Closed as completed by kantlivelong** 2020-06-07 20:39 UTC
